{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "96905a58-4d9a-4afa-8832-bf00d432f044",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (3321507479.py, line 97)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 97\u001b[1;36m\u001b[0m\n\u001b[1;33m    ```\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "# ===============================\n",
    "# PAGE CONFIG\n",
    "# ===============================\n",
    "st.set_page_config(\n",
    "    page_title=\"CICIDS2017 Intrusion Detection\",\n",
    "    page_icon=\"🛡️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# LOAD MODEL & SCALER\n",
    "# ===============================\n",
    "model = joblib.load(\"random_forest_cicids2017.pkl\")\n",
    "scaler = joblib.load(\"scaler_cicids2017.pkl\")\n",
    "\n",
    "# ===============================\n",
    "# UI HEADER\n",
    "# ===============================\n",
    "st.title(\"🛡️ Network Intrusion Detection System\")\n",
    "st.markdown(\"Detect **Normal vs Attack** traffic using Machine Learning (Random Forest + CICIDS2017)\")\n",
    "\n",
    "st.sidebar.title(\"⚙️ Controls\")\n",
    "option = st.sidebar.radio(\"Choose Input Method:\", [\"Upload CSV\", \"Manual Input (Simple Test)\"])\n",
    "\n",
    "# ===============================\n",
    "# CSV UPLOAD MODE\n",
    "# ===============================\n",
    "if option == \"Upload CSV\":\n",
    "    file = st.file_uploader(\"Upload Network Traffic CSV\", type=[\"csv\"])\n",
    "\n",
    "    if file is not None:\n",
    "        df = pd.read_csv(file)\n",
    "\n",
    "        st.write(\"### Preview of Data\")\n",
    "        st.dataframe(df.head())\n",
    "\n",
    "        # preprocessing\n",
    "        df = df.replace([np.inf, -np.inf], np.nan)\n",
    "        df = df.fillna(0)\n",
    "\n",
    "        # encode categorical\n",
    "        for col in df.columns:\n",
    "            if df[col].dtype == 'object':\n",
    "                df[col] = df[col].astype(str).factorize()[0]\n",
    "\n",
    "        # scaling\n",
    "        X = scaler.transform(df)\n",
    "\n",
    "        # prediction\n",
    "        preds = model.predict(X)\n",
    "\n",
    "        df[\"Prediction\"] = np.where(preds == 0, \"BENIGN\", \"ATTACK\")\n",
    "\n",
    "        st.write(\"### Results\")\n",
    "        st.dataframe(df)\n",
    "\n",
    "        st.success(\"Prediction Completed ✔\")\n",
    "\n",
    "# ===============================\n",
    "# SIMPLE MANUAL TEST MODE\n",
    "# ===============================\n",
    "else:\n",
    "    st.write(\"### Enter Sample Values\")\n",
    "\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "\n",
    "    with col1:\n",
    "        f1 = st.number_input(\"Feature 1\", value=0.0)\n",
    "        f2 = st.number_input(\"Feature 2\", value=0.0)\n",
    "        f3 = st.number_input(\"Feature 3\", value=0.0)\n",
    "\n",
    "    with col2:\n",
    "        f4 = st.number_input(\"Feature 4\", value=0.0)\n",
    "        f5 = st.number_input(\"Feature 5\", value=0.0)\n",
    "        f6 = st.number_input(\"Feature 6\", value=0.0)\n",
    "\n",
    "    with col3:\n",
    "        f7 = st.number_input(\"Feature 7\", value=0.0)\n",
    "        f8 = st.number_input(\"Feature 8\", value=0.0)\n",
    "        f9 = st.number_input(\"Feature 9\", value=0.0)\n",
    "\n",
    "    if st.button(\"Predict 🚀\"):\n",
    "        sample = np.array([[f1, f2, f3, f4, f5, f6, f7, f8, f9]])\n",
    "\n",
    "        sample_scaled = scaler.transform(sample)\n",
    "        result = model.predict(sample_scaled)[0]\n",
    "\n",
    "        if result == 0:\n",
    "            st.success(\"✔ BENIGN (Normal Traffic)\")\n",
    "        else:\n",
    "            st.error(\"🚨 ATTACK DETECTED\")\n",
    "```\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
